# Generated by Django 2.2.7 on 2020-05-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0053_auto_20191114_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplatformmetacritic',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
