# Generated by Django 2.2.15 on 2020-12-16 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0054_gameplatformmetacritic_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ('-games_added',), 'verbose_name': 'Developer', 'verbose_name_plural': 'Developers'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ('-games_added',), 'verbose_name': 'Publisher', 'verbose_name_plural': 'Publishers'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-games_added',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.RemoveField(
            model_name='developer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='order',
        ),
    ]
