# Generated by Django 2.2.27 on 2022-07-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0057_auto_20210315_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='iframe',
            field=models.URLField(blank=True, default=''),
        ),
    ]
