# Generated by Django 2.2.27 on 2022-09-16 14:13

from django.core.paginator import Paginator
from django.db import migrations

from apps.games.models import generate_secret_key


def make_secrets(apps, schema_editor):
    game_model = apps.get_model('games', 'Game')
    paginator = Paginator(game_model.objects.only('secret_key'), 5000)
    for page_number in paginator.page_range:
        changed = []
        for game in paginator.page(page_number):
            game.secret_key = generate_secret_key()
            changed.append(game)
        batch_size = 999 if schema_editor.connection.vendor == 'sqlite' else None
        game_model.objects.bulk_update(changed, ['secret_key'], batch_size)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0059_auto_20220915_2102'),
    ]

    operations = [
        migrations.RunPython(make_secrets, migrations.RunPython.noop)
    ]
