# Generated by Django 2.2.27 on 2022-09-16 14:13

import django.core.validators
from django.db import migrations, models

import apps.games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0060_auto_20220916_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='secret_key',
            field=models.CharField(
                editable=False,
                max_length=50,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(40)],
                verbose_name='секретный ключ',
                default=apps.games.models.generate_secret_key,
            ),
        ),
    ]
