# Generated by Django 2.2 on 2022-11-25 11:32

import apps.games.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0061_auto_20220916_1413'),
        ('users', '0028_auto_20221125_1132')
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_sid', models.CharField(default=apps.games.models.generate_game_sid, editable=False, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(40)], verbose_name='id сессии')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='время создания')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playergamesession_through', to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playergamesession_through', to=settings.AUTH_USER_MODEL, to_field='player_id')),
            ],
            options={
                'verbose_name': 'сессия игрока в игре',
                'verbose_name_plural': 'сессии игроков в играх',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='users_played',
            field=models.ManyToManyField(related_name='games_played', through='games.PlayerGameSession', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='playergamesession',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='playergamesession_unique_relation'),
        ),
    ]
