# Generated by Django 2.2 on 2022-11-25 13:16

import apps.games.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0062_auto_20221125_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGameSessionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(storage=apps.games.models.games_file_storage, upload_to=apps.games.models.game_session_data_path, verbose_name='файл данных сессии')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='время создания')),
                ('session', models.OneToOneField(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='data', to='games.PlayerGameSession', to_field='game_sid', verbose_name='игровая сессия')),
            ],
            options={
                'verbose_name': 'данные игровой сессии',
                'verbose_name_plural': 'данные игровых сессий',
            },
        ),
    ]
