# Generated by Django 2.2 on 2023-01-16 10:47

import apps.games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0063_playergamesessiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='description',
            field=models.TextField(blank=True, max_length=255, verbose_name='описание в каруселе'),
        ),
        migrations.AddField(
            model_name='featured',
            name='image',
            field=models.ImageField(help_text='1154x640, JPG', upload_to=apps.games.models.featured_image, verbose_name='картинка в каруселе'),
        ),
    ]
