# Generated by Django 2.2 on 2023-01-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0064_auto_20230116_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='webhook_url',
            field=models.URLField(blank=True, verbose_name='вебхук игры'),
        ),
    ]
