# Generated by Django 2.2 on 2023-05-19 12:53

import apps.games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0066_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured',
            name='image_mobile',
            field=models.ImageField(blank=True, upload_to=apps.games.models.featured_image_mobile, verbose_name='картинка для мобильных устройств'),
        ),
    ]
