# Generated by Django 2.2 on 2023-06-09 13:13

from django.db import migrations


def allow_playable_games_on_all_site_versions(apps, schema_editor):
    game_model = apps.get_model('games', 'Game')
    game_model.objects.filter(can_play=True).exclude(iframe='').update(play_on_desktop=True, play_on_mobile=True)


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0068_auto_20230609_1309'),
    ]

    operations = [
        migrations.RunPython(allow_playable_games_on_all_site_versions, migrations.RunPython.noop),
    ]
