# Generated by Django 2.2 on 2023-07-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0069_data_all_platforms_for_playable_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='plays',
            field=models.PositiveIntegerField(default=0, verbose_name='number of plays'),
        ),
    ]
