# Generated by Django 2.2 on 2023-08-03 12:17

from django.db import migrations


def fill_seamless_auth(apps, schema_editor):
    game_model = apps.get_model('games', 'Game')
    game_model.objects.filter(can_play=True).update(seamless_auth=False)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0071_game_seamless_auth'),
    ]

    operations = [
        migrations.RunPython(fill_seamless_auth, migrations.RunPython.noop)
    ]
