# Generated by Django 2.2 on 2023-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0072_data_fill_seamless_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='alternative_fullscreen',
            field=models.BooleanField(blank=True, null=True, verbose_name='Альтернативная работа с Fullscreen'),
        ),
    ]
