# Generated by Django 2.2 on 2023-08-03 12:21

from django.db import migrations


def fill_alternative_fullscreen(apps, schema_editor):
    game_model = apps.get_model('games', 'Game')
    game_model.objects.filter(can_play=True).update(alternative_fullscreen=False)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0073_game_alternative_fullscreen'),
    ]

    operations = [
        migrations.RunPython(fill_alternative_fullscreen, migrations.RunPython.noop)
    ]
