# Generated by Django 2.2 on 2023-08-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0074_data_fill_alternative_fullscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description_short',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='game',
            name='description_short_en',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='description_short_ru',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
