# Generated by Django 2.2 on 2023-12-27 03:04

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0075_auto_20230830_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='exit_button_position',
            field=models.CharField(blank=True, help_text='Два значения без пробелов и через запятую в пикселях и/или процентах, например: "1px,5%"', max_length=20, validators=[django.core.validators.RegexValidator('^([0-9]+(px|%)),([0-9]+(px|%))$', flags=re.RegexFlag(256))], verbose_name='Положение кнопки выхода из игры'),
        ),
    ]
