# Generated by Django 2.2 on 2024-03-02 08:10

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0076_game_exit_button_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadWorldNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=600)),
                ('board', models.CharField(choices=[('notice', 'Notice'), ('gmboard', 'GMBoard')], max_length=30)),
                ('wr_id', models.PositiveIntegerField(db_index=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'MadWorld in-game news',
                'verbose_name_plural': 'MadWord in-game news',
                'ordering': ('-published', '-id'),
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='madworldnews',
            constraint=models.UniqueConstraint(fields=('wr_id', 'board'), name='unique_wr_id_board'),
        ),
    ]
