# Generated by Django 2.2 on 2023-11-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0077_auto_20240302_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='local_client',
            field=models.BooleanField(default=None, null=True, verbose_name='есть локальный клиент'),
        ),
    ]
