# Generated by Django 2.2.15 on 2020-08-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stat', '0007_apibyipanduseragentvisit_apibyipvisit_apibyuseragentvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apibyipanduseragentvisit',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='apibyipvisit',
            old_name='datetime',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='apibyuseragentvisit',
            old_name='datetime',
            new_name='date',
        ),
        migrations.AddField(
            model_name='apibyipanduseragentvisit',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='apibyipvisit',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='apibyuseragentvisit',
            name='count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='apibyipanduseragentvisit',
            name='ip',
            field=models.CharField(editable=False, max_length=45),
        ),
        migrations.AlterField(
            model_name='apibyipvisit',
            name='ip',
            field=models.CharField(editable=False, max_length=45),
        ),
    ]
