# Generated by Django 2.2 on 2023-09-23 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stat', '0010_apiusercounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
