# Generated by Django 2.2.27 on 2022-09-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_data_migration_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='player_id',
            field=models.UUIDField(null=True, editable=False, verbose_name='id игрока'),
        ),
    ]
