# Generated by Django 2.2.27 on 2022-09-15 21:17
from django.db import migrations
from django.core.paginator import Paginator

from apps.users.models import PlayerBase


def gen_player_id(apps, schema_editor):
    user_model = apps.get_model('users', 'User')
    paginator = Paginator(user_model.objects.only('player_id'), 5000)
    for page_number in paginator.page_range:
        changed = []
        for user in paginator.page(page_number):
            user.player_id = PlayerBase.generate_id()
            changed.append(user)
        batch_size = 999 if schema_editor.connection.vendor == 'sqlite' else None
        user_model.objects.bulk_update(changed, ['player_id'], batch_size)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_player_id'),
    ]

    operations = [
        migrations.RunPython(gen_player_id, migrations.RunPython.noop)
    ]
