# Generated by Django 2.2.27 on 2022-09-15 21:17
from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220915_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='player_id',
            field=models.UUIDField(default=apps.users.models.PlayerBase.generate_id, unique=True, editable=False, verbose_name='id игрока'),
        ),
    ]
