# Generated by Django 2.2.27 on 2022-10-08 14:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.users.models
from apps.games.models import generate_game_sid
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0061_auto_20220916_1413'),
        ('users', '0026_auto_20220915_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_sid', models.CharField(default=generate_game_sid, editable=False, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(40)], verbose_name='игровая сессия')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playergame_through', to='games.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playergame_through', to=settings.AUTH_USER_MODEL, to_field='player_id')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='время создания сессии')),
            ],
            options={
                'verbose_name': 'связь игрока и игры',
                'verbose_name_plural': 'связи игроков и игр',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='games_played',
            field=models.ManyToManyField(related_name='users_played', through='users.PlayerGame', to='games.Game'),
        ),
        migrations.AddConstraint(
            model_name='playergame',
            constraint=models.UniqueConstraint(fields=('game', 'player'), name='player_game_unique_relation'),
        ),
    ]
