# Generated by Django 2.2 on 2022-11-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20221008_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='games_played',
        ),
        migrations.DeleteModel(
            name='PlayerGame',
        ),
    ]
