# Generated by Django 2.2 on 2023-09-15 15:32

from django.db import migrations


def create_balances(apps, schema_editor):
    balance_model = apps.get_model('users', 'Balance')
    user_model = apps.get_model('users', 'User')

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'INSERT INTO {balance_model._meta.db_table} (user_id, bonuses) '
            f'SELECT id, 0.0 FROM {user_model._meta.db_table};'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20230914_0808'),
    ]

    operations = [
        migrations.RunPython(create_balances, migrations.RunPython.noop)
    ]
