# Generated by Django 2.2 on 2023-11-30 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0075_auto_20230830_1210'),
        ('users', '0030_create_user_balances'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('betatest', 'Beta test subscription')], max_length=20)),
                ('reward_bonus', models.PositiveSmallIntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
            ],
            options={
                'verbose_name': 'Game status subscription program',
                'verbose_name_plural': 'Game status subscription programs',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SubscriptionProgram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game status subscription',
                'verbose_name_plural': 'Game status subscriptions',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionprogram',
            constraint=models.UniqueConstraint(fields=('game', 'status'), name='sub_program_game_status_unique_constraint'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('user', 'program'), name='sub_user_game_unique_constraint'),
        ),
    ]
