import requests
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    def handle(self, *args, **options):
        api_address = f'https://{settings.ALLOWED_HOSTS[0]}'
        data = [
            ['runescape', 'Runespell: Overture', 'RuneScape'],
            ['albion online', 'Jagged Alliance Online', 'Albion Online'],
            ['factorio', 'Red Faction: Armageddon', 'Factorio'],
            ['Factorio', 'Red Faction: Armageddon', 'Factorio'],
            ['Kenshi', 'Persona 5', 'Kenshi'],
            ['Bioshock', 'BioShock Infinite', 'BioShock'],
            ['F.E.A.R.', 'F.E.A.R. 3', 'F.E.A.R.'],
            ['Mass Effect', 'Mass Effect 2', 'Mass Effect'],
            ['Heliophobia', 'Hellphobia', 'Heliophobia'],
            ['Portal', 'Portal 2', 'Portal'],
            ['Pariah', 'Parkan 2', 'Pariah'],
            ['DOMINA', 'Binary Domain', 'Domina'],
            ['Wandersong', "Luna's Wandering Stars", 'Wandersong'],
            ['Deus Ex', 'Deus Ex: Mankind Divided', 'Deus Ex'],
            ['Killer is Dead', 'Killer is Dead - Nightmare Edition', 'KILLER IS DEAD'],
            ['The Initial', 'Data Hacker: Initiation', 'The Initial'],
            ["Dragon's Dogma", "Dragon's Dogma: Dark Arisen", "Dragon's Dogma"],
            ['Risk of Rain', 'Rise of the Tomb Raider', 'Risk of Rain'],
            ['Ruiner', 'Tomb Raider (2013)', 'RUINER'],
            ['Shadow of Mordor', 'Middle-earth: Shadow of Mordor', 'Middle-earth: Shadow of Mordor'],
            ['Shadow of War', 'Middle-earth: Shadow of War', 'Shadows of War'],
            ['SOMA', 'Binary Domain', 'SOMA'],
            ['Titan Quest', 'Titan Quest Anniversary Edition', 'Titan Quest'],
            ['Furi', 'Serious Sam Fusion 2017 (beta)', 'Furi'],
            ['Tacoma', 'Thomas Was Alone', 'Tacoma'],
            ['Guacamelee', 'Guacamelee! Super Turbo Championship Edition', 'Guacamelee!'],
            ['Shantae', 'Shatter', 'Shantae'],
            ['Infliction', "Infection: Humanity's Last Gasp", 'Infliction'],
            ['Penumbra', 'Penumbra Overture', 'Penumbra'],
            ['Visage', 'Viscera Cleanup Detail: Shadow Warrior', 'Visage'],
            ['0', 'RACE 07', '0'],
            ['DESOLATE', 'The Desolate Hope', 'DESOLATE'],
            ['The Forest', 'Ori and the Blind Forest', 'The Forest'],
            ['Shadow Warrior', 'Viscera Cleanup Detail: Shadow Warrior', 'Shadow Warrior'],
            ['The Thing', 'The Next BIG Thing', 'The Thing With Mistletoes'],
            ['Devil May Cry', 'DmC: Devil May Cry', 'Devil May Cry'],
            ['Reventa', 'METAL GEAR RISING: REVENGEANCE', 'Reventa'],
            ['Resident Evil Remaster', 'Resident Evil / biohazard HD REMASTER', 'Resident Evil HD Remaster'],
            ['Silent Hill', 'Silent Hill Homecoming', 'Silent Hill'],
            ['Elder Scrolls Online', 'The Elder Scrolls Online: Tamriel Unlimited', 'The Elder Scrolls Online'],
            ['re', 'Red Dead Redemption 2', 'RE'],
            ['Psi-Ops', "Recettear: An Item Shop's Tale", 'Psion'],
            ['Second Sight', 'Nightork Adventures - Beyond the Moons of Shadalee', 'Second Sight'],
            ['Star Wars - Jedi Knight Jedi Academy', 'STAR WARS Jedi Knight - Jedi Academy',
             'Star Wars Jedi Knight: Jedi Academy'],
            ['Star Wars - Jedi Knight Jedi Outcast', 'STAR WARS Jedi Knight II - Jedi Outcast',
             'Star Wars Jedi Knight II: Jedi Outcast'],
            ['The Darkness', 'Amnesia: The Dark Descent', 'The Darkness'],
            ['Pathologic', 'Pathologic Classic HD', 'Pathologic 2'],
            ['Star Wars - Jedi Knght Jedi Academy', 'STAR WARS Jedi Knight - Jedi Academy',
             'Star Wars Jedi Knight: Jedi Academy'],
            ['Star Wars - Jedi Knght Jedi Outcast', 'STAR WARS Jedi Knight II - Jedi Outcast',
             'Star Wars Jedi Knight II: Jedi Outcast'],
            ['Elderborn', 'Etherborn', 'ELDERBORN'],
            ['Wolfenstein', 'Wolfenstein: The New Order', 'Wolfenstein'],
            ['The Witcher', 'The Witcher 3: Wild Hunt', 'The Witcher'],
            ['NieR', 'NieR:Automata', 'NIER'],
            ['Planescape Torment', 'Planescape: Torment: Enhanced Edition', 'Planescape: Torment'],
            ['{Okami}', 'OKAMI HD / 大神 絶景版', 'Okami'],
            ['Gris', 'Rise of the Tomb Raider', 'Gris'],
            ['Max Payne', 'Max Payne 3', 'Max Payne'],
            ['Anima: Gate of Memories', 'Anima Gate of Memories', 'Anima: Gate of memories'],
            ['The Vagrant', 'Valiant Hearts: The Great War', 'The Vagrant'],
            ['Legacy of the Wizard', 'Wizardry 3: The Legacy of Llylgamyn', 'Legacy of the Wizard'],
            ['Shadowgate', 'Shadowgate (2014)', 'Shadowgate'],
            ['Dynasty Wars', 'DYNASTY WARRIORS NEXT', 'Dynasty Wars'],
            ['Street Fighter 2', "Street Fighter II' HF", 'Street Fighter 2'],
            ['Street Fighter II', "Street Fighter II' HF", 'Street Fighter 2'],
            ['Legacy of the Lizard', 'Wizardry 3: The Legacy of Llylgamyn', 'Legacy of the Wizard'],
            ['Resident Evil 2', 'Resident Evil Revelations 2 / Biohazard Revelations 2', 'Resident Evil 2'],
            ['Kingdom Hearts III', 'Kingdom Hearts 358/2 Days', 'Kingdom Hearts III'],
            ['Cinders', 'Age of Wonders III', 'Cinders'],
            ['Fable', 'Lords of the Fallen', 'Fable III'],
            ['Hard Reset', 'Hard Reset Extended Edition', 'Hard Reset'],
            ['Dragon Age', 'Dragon Age: Origins', 'Dragon Age 2'],
            ['Ys:Origins', 'Batman: Arkham Origins', 'Yesterday Origins'],
            ['Donkey Kong Country', 'Donkey Kong Country: Tropical Freeze', 'Donkey Kong Country'],
            ['Sanctum', 'Sanctum 2', 'Sanctum'],
            ['Ashen', 'TowerFall Ascension', 'Ashen'],
            ['{The Forest}', 'Ori and the Blind Forest', 'The Forest'],
            ["Don't Starve", "Don't Starve Together", "Don't Starve"],
            ['Evolution', 'Deus Ex: Human Revolution', 'Evolution'],
            ['Abzu', 'A Story About My Uncle', 'ABZU'],
            ['Moonlighter', 'Momodora: Reverie Under the Moonlight', 'Moonlighter'],
            ['htoL#NiQ: The Firefly Diary', 'Hotline Miami', 'Hollow Knight'],
            ['Nelo', 'Counter-Strike Nexon: Zombies', 'Nelo'],
            ['Rising Islands', "Galagan's Island: Reprymian Rising", 'Rising Islands'],
            ['Deadly Premonition', "Deadly Premonition: The Director's Cut", 'DEADLY PREMONITION'],
            ['Request', 'Titan Quest Anniversary Edition', 'Request'],
            ['F.E.A.R', 'F.E.A.R. 3', 'F.E.A.R.'],
            ['Elemental', 'Transmissions: Element 120', 'Elementals'],
            ['Killer7', 'Killer is Dead - Nightmare Edition', 'killer7'],
            ['F.E.A.R:', 'F.E.A.R. 3', 'F.E.A.R.'],
            ['Blood', 'Bloodborne', 'Blood'],
            ['Call of Juarez', 'Call of Juarez Gunslinger', 'Call of Juarez'],
            ['Sniper Elite', 'Sniper Elite V2', 'Sniper Elite'],
            ['Vanguish', 'The Vanishing of Ethan Carter', 'Anguish'],
            ['Chrome', 'Game of Thrones - A Telltale Games Series', 'Neon Chrome'],
            ['Chaser', 'Fable - The Lost Chapters', 'CHASERS'],
            ['Mulaka', 'La-Mulana', 'Mulaka'],
            ['New Super Mario Bros.', 'New Super Mario Bros. Wii', 'New Super Mario Bros.'],
            ['Sam & Max', 'Serious Sam Fusion 2017 (beta)', "Sam & Max 303: They Stole Max's Brain!"],
            ['Vampyr', 'Valkyria Chronicles', 'Vampyr'],
            ['Venetica', 'Vertical Drop Heroes HD', 'Venetica'],
            ['Tomb Raider', 'Tomb Raider (2013)', 'Tomb Raider'],
            ['Sundered', 'Murdered: Soul Suspect', 'Sundered'],
            ['Half-Life', 'HalfLight', 'Pocket HalfPipe'],
            ['Dark Souls', 'DARK SOULS III', 'Dark Souls'],
            ['Alice; Madness Returns', 'Alien: Isolation', 'Alice: Madness Returns'],
            ['Rain World', 'Table Top Racing: World Tour', 'Rain World'],
            ['Castlevania: Lords of Shadow', 'Castlevania: Lords of Shadow â€" Ultimate Edition',
             'Castlevania: Lords of Shadow'],
            ['Orphan', 'METAL GEAR SOLID V: THE PHANTOM PAIN', 'Orphan'],
            ['Crysis', 'Crysis 2 - Maximum Edition', 'Crysis'],
            ['Blood 2: The Chosen', 'Blood II: The Chosen + Expansion', 'Blood 2: The Chosen'],
            ['Eye', "Edna & Harvey: Harvey's New Eyes", 'EYE'],
            ['Hate', 'Hand of Fate', 'The Hateful Dead'],
            ['People', 'Lara Croft and the Temple of Osiris', 'People'],
            ['have', 'Cave Story+', 'You Have to Win the Game'],
            ['done', "Don't Starve Together", 'It Is Done'],
            ['years', 'Batman: Arkham City - Game of the Year Edition', '400 Years'],
            ['single', 'The Ship: Single Player', 'single'],
            ['bust', 'Bastion', 'Busted'],
            ['Thanks', 'World of Tanks', 'Thanksgiving'],
            ['goal', 'Goat Simulator', 'Goal!'],
            ['obtained', 'Stained', 'ABOMINATION OBTAINER'],
            ['which', 'Which Naruto character are you?', 'Which ?'],
            ['used', "Penguins Arena: Sedna's World", 'Best If Used By'],
            ['build', 'The Guild II', 'Ace of Spades: Battle Builder'],
            ['that', 'FTL: Faster Than Light', 'Sam & Max 305: The City That Dares Not Sleep'],
            ['deletes', 'The Deletion', 'Delete'],
            ['when', 'Action Henk', 'When Vikings Attack!'],
            ['loads', 'Lords of the Fallen', 'Block N Load'],
            ['type', 'Hyper Light Drifter', 'Type:Rider'],
            ['currently', 'Melty Blood Actress Again Current Code', 'Currently Running Processes'],
            ['hospital', 'Hospital Tycoon', 'Hospital'],
            ['dying', 'DARK SOULS: Prepare To Die Edition', 'Dying'],
            ['terminal', 'Terminator Salvation', 'Terminal Velocity'],
            [' disease', 'World of Guns: Gun Disassembly', 'DISEASED: Retribution'],
            ['however', 'Duke Nukem Forever', 'The Howler'],
            [' this', 'Saints Row: The Third', 'This War of Mine'],
            ['victory', 'Victor Vran', 'Sniper Art of Victory'],
            ['72', 'Iron Warriors: T - 72 Tank Command', '72'],
            ['hours', "Monaco: What's Yours Is Mine", '24 HOURS'],
            ['expected', 'Saints Row IV: Re-Elected', 'Unexpected Day'],
            ['die', 'DARK SOULS: Prepare To Die Edition', 'Die'],
            ['Wish', 'Dishonored', 'Fish Wishes'],
            ['luck', 'Lucius', "Super Lucky's Tale"],
            ['this', 'Saints Row: The Third', 'This War of Mine'],
            ['final', 'FINAL FANTASY XV', 'Finale'],
            ['Morphite', 'Morphine', 'Morphite'],
            ['Memento', 'Death to Spies: Moment of Truth', 'Memento'],
            ['Adventure Island', "Robin's Island Adventure", 'Adventure Island 3'],
            ['XCOM2', 'XCOM: Enemy Unknown', 'XCOM 2'],
            ['The Sims', 'The Sims 3', 'The Sims'],
            ['Haydee', 'Yooka-Laylee', 'Haydee'],
            ['The Dream Machine', 'The Dream Machine: Chapter 1 & 2', 'The Dream Machine'],
            ['Stronghold', 'Stronghold Crusader HD', 'Strongholds'],
            ['Sacred', "Hellblade: Senua's Sacrifice", 'Sacred'],
            ['Beyond Good and Evil', 'Beyond Good & Evil', 'Beyond Good and Evil 2'],
            ['Call of Cthulhu', 'Call of Cthulhu: Dark Corners of the Earth', 'Call of Cthulhu'],
            ['Hunt; Showdown', 'The Witcher 3: Wild Hunt', 'Monster Hunter: World'],
            ['Loot Box Simulator', 'Loot Box Simulator 20!8', 'Loot Box Simulator'],
            ['Worlds Adrift', 'Worlds Adrift Island Creator', 'Worlds Adrift'],
            ['Screeps', 'Screencheat', 'Screeps'],
            ['Threes!', "Uncharted 4: A Thief's End", 'Threes!'],
            ['Diablo', 'Diablo III: Reaper of Souls', 'Diablo'],
            ['Cold Fear', "Melissa K. and the Heart of Gold Collector's Edition", 'Cold Fear'],
            ['RUINER', 'Tomb Raider (2013)', 'RUINER'],
            ['Observer', '>observer_', '>observer_'],
            ['Atelier Lydie&Suelle', 'Atelier Lydie & Suelle ~The Alchemists and the Mysterious Paintings~',
             'Atelier Lydie & Suelle'],
            ['Last Remnant', 'The Last Of Us Remastered', 'The Last Remnant'],
            ['Burnout Paradise', 'Burnout Paradise: The Ultimate Box', 'Burnout Paradise'],
            ['Fuel', 'Minion Masters', 'FUEL'],
            ['The Elder Scrolls IV Oblivion', 'The Elder Scrolls IV: Oblivion Game of the Year Edition',
             'The Elder Scrolls IV: Oblivion'],
            ['The Elder Scrolls III Morrowind', 'The Elder Scrolls III: Morrowind Game of the Year Edition',
             'The Elder Scrolls 3: Morrowind'],
            ['Divinity: Original Sin', 'Divinity: Original Sin - Enhanced Edition', 'Divinity: Original Sin'],
            ['Risen', 'Rise of the Tomb Raider', 'Risen'],
            ['Elex', 'Rome: Total War - Alexander', 'ELEX'],
            ['Info', 'BioShock Infinite', 'Raft-Info'],
            ['Contact', "Tom Clancy's Splinter Cell: Conviction", 'Contact'],
            ['Anthem', 'Yet Another Zombie Defense', 'Anthem'],
            ['Fall of Light', 'Dark Fall 2: Lights Out', 'Fall of Light'],
            ['SIlent Hill', 'Silent Hill Homecoming', 'Silent Hill'],
            ['Dauntless', 'Survivor Squad: Gauntlets', 'Dauntless'],
            ['kenshi', 'Persona 5', 'Kenshi'],
            ['Outward', 'Outland', 'Outward'],
            ['Devil May Cry 3', 'Devil May Cry 3 Special Edition', 'Devil May Cry 3'],
            ['KeeperRL', 'Runestone Keeper', 'KeeperRL'],
            ['Eco', 'Ecolibrium', 'Eco'],
            ['Avorion', 'ORION: Prelude', 'Avorion'],
            ['XCOM 2', 'Trine 2: Complete Story', 'XCOM 2'],
            ['Torchlight', 'Torchlight II', 'Torchlight'],
            ['Golden Sun', 'Golden Sun (2001)', 'Golden Sun'],
            ['Rakuen', 'METAL GEAR RISING: REVENGEANCE', 'Rakuen'],
            ['Metro Last Light', 'Metro: Last Light Redux', 'Metro: Last Light'],
            ['Penumbra: Black Plague', 'Penumbra: Black Plague Gold Edition', 'Penumbra: Black Plague'],
            ['Penumbra: Overture', 'Penumbra Overture', 'Penumbra: Overture'],
            ['Mount & Blade: Warband', 'Counter-Strike: Global Offensive', 'Mount & Blade: Warband'],
            ['/r/gaming', 'RaceRoom Racing Experience', 'Platforms (GamingNinja)'],
            ['Outcast', 'Outlast', 'Outcast'],
            ['The Devil Inside', 'Resident Evil: The Umbrella Chronicles', 'Devil Inside'],
        ]
        error = False
        for query, old_api, bot in data:
            results = requests.get(
                f'{api_address}/api/games',
                {'search': query, 'key': get_user_model().objects.order_by('id').first().api_key},
                headers={'Host': settings.ALLOWED_HOSTS[0], 'User-Agent': 'check_search'},
            ).json()['results']
            new_api = results[0]['name'] if results else ''
            new_api_compare = new_api.split('(')[0].strip()
            style = self.style.SUCCESS
            if new_api_compare != bot and new_api_compare != query:
                style = self.style.ERROR
                error = True
                if query != bot:
                    style = self.style.WARNING
                    error = False
            if style == self.style.ERROR or settings.DEBUG:
                self.stdout.write(style(f'QUERY: {query} - OLD API: {old_api} - BOT: {bot} - NEW API: {new_api}'))
        self.stdout.write(self.style.SUCCESS('OK') if not error else self.style.ERROR('ERROR'))
        if error:
            exit(1)
