# Generated by Django 4.2.23 on 2025-06-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='launch_url',
            field=models.CharField(max_length=255),
        ),
    ]
