# Generated by Django 4.2.23 on 2025-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_launch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
