# Generated by Django 4.2.23 on 2025-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_opens'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('action', 'Action'), ('puzzle', 'Puzzle'), ('casual', 'Casual'), ('strategy', 'Strategy')], default='casual', max_length=20),
        ),
    ]
