export default {
  id: 2269437,
  user: {
    id: 3092,
    username: 'arikuza',
    slug: 'arikuza',
    full_name: '',
    avatar: 'https://devapi.rawg.io/media/avatars/e40/e4096c21482f7e7b43cd3e8941942c5e.png',
    games_count: 173,
    collections_count: 4,
    following: false,
  },
  reactions: [],
  action: 'followed_user',
  created: '2018-04-06T11:41:48.266751Z',
  users: {
    count: 6,
    results: [
      {
        id: 5425,
        username: 'Lagsalot',
        slug: 'lagsalot',
        full_name: 'Sir Lagsalot',
        avatar: null,
        games_count: 204,
        collections_count: 3,
        following: true,
      },
      {
        id: 27,
        username: 'iBarin',
        slug: 'ibarin',
        full_name: 'pathBarin',
        avatar: null,
        games_count: 344,
        collections_count: 5,
        following: true,
      },
      {
        id: 54,
        username: 'elCT',
        slug: 'elct',
        full_name: 'Sergey Ulankin',
        avatar: null,
        games_count: 120,
        collections_count: 6,
        following: true,
      },
      {
        id: 1923,
        username: 'andreyk',
        slug: 'andreyk',
        full_name: '',
        avatar: null,
        games_count: 17,
        collections_count: 2,
        following: true,
      },
      {
        id: 2290,
        username: 'rawg_editorial',
        slug: 'rawg_editorial',
        full_name: 'RAWG Editorial',
        avatar: null,
        games_count: 45,
        collections_count: 58,
        following: true,
      },
      {
        id: 3,
        username: 'sinkler',
        slug: 'sinkler',
        full_name: 'Sinkler',
        avatar: null,
        games_count: 211,
        collections_count: 1,
        following: true,
      },
    ],
  },
};
