# Generated by Django 2.2.27 on 2022-12-09 16:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0063_playergamesessiondata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XsollaProject',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id проекта')),
                ('secret_key', models.CharField(max_length=100, verbose_name='секретный ключ')),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.Game', verbose_name='игра')),
            ],
            options={
                'verbose_name': 'проект Xsolla',
                'verbose_name_plural': 'проекты Xsolla',
            },
        ),
        migrations.CreateModel(
            name='XsollaTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(db_index=True, max_length=100)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.PositiveIntegerField(unique=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.XsollaProject')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='player_id')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'транзакция Xsolla',
                'verbose_name_plural': 'транзакции Xsolla',
            },
        ),
    ]
