# Generated by Django 2.2 on 2023-01-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0065_game_webhook_url'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xsollatransaction',
            name='game_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.PlayerGameSession', to_field='game_sid'),
        ),
    ]
