# Generated by Django 2.2 on 2023-04-24 12:22

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now

import apps.payments.models
import apps.payments.utils


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0066_recommended'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_xsollatransaction_game_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('initial', 'initial state'), ('created', 'game requested a token'), ('pending', 'pending player payment'), ('canceled', 'payment token expired'), ('paid', 'paid'), ('payment_confirmed', 'game confirmed payment'), ('refunded', 'refunded'), ('refund_confirmed', 'refund confirmed'), ('error', 'error')], max_length=32, verbose_name='state')),
                ('created', models.DateTimeField(default=now)),
                ('token', models.CharField(default=apps.payments.models.generate_token, editable=False, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(40)], verbose_name='token')),
                ('game', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='games.Game')),
                ('game_session', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.PlayerGameSession', to_field='game_sid')),
                ('payment_system_name', models.CharField(choices=[('xsolla', 'Xsolla'), ('ukassa', 'Ukassa')], max_length=20, blank=True)),
            ],
            options={
                'verbose_name': 'состояние процесса оплаты',
                'verbose_name_plural': 'состояния процессов оплаты',
                'ordering': ('id',),
            },
            bases=(apps.payments.utils.PaymentStateMachineMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_event_type', models.CharField(db_index=True, editable=False, max_length=32)),
                ('created', models.DateTimeField(default=now)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(editable=False, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('payment', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='payment_events', to='payments.Payment')),
            ],
            options={
                'verbose_name': 'событие процесса оплаты',
                'verbose_name_plural': 'события процесса оплаты',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='last_success_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.PaymentEvent'),
        ),
        migrations.AddField(
            model_name='payment',
            name='player',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='player_id'),
        ),
        migrations.CreateModel(
            name='CreatedEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentevent',),
        ),
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentevent',),
        ),
        migrations.CreateModel(
            name='PaidEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentevent',),
        ),
        migrations.CreateModel(
            name='PaymentConfirmedEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentevent',),
        ),
        migrations.CreateModel(
            name='PendingEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentevent',),
        ),
        migrations.CreateModel(
            name='RefundConfirmedEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentevent',),
        ),
        migrations.CreateModel(
            name='RefundedEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentevent',),
        ),
        migrations.CreateModel(
            name='CanceledEvent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.paymentevent',),
        ),
        migrations.CreateModel(
            name='PaymentProject',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='id проекта')),
                ('payment_system_name', models.CharField(choices=[('xsolla', 'Xsolla'), ('ukassa', 'Ukassa')], max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game', verbose_name='игра')),
                ('secret_key', models.CharField(max_length=255, verbose_name='секретный ключ')),
            ],
            options={
                'verbose_name': 'Проект игры в платёжной системе',
                'verbose_name_plural': 'Проекты игры в платёжной системе'
            },
        ),
        migrations.AddConstraint(
            model_name='paymentproject',
            constraint=models.UniqueConstraint(fields=('payment_system_name', 'game'), name='paymentproject_game_unique'),
        ),
    ]
