# Generated by Django 2.2 on 2023-05-07 04:43

from django.db import connection, migrations

INDEX_NAME = 'json_event_data_id_index'


def create_index(apps, schema_editor):
    model = apps.get_model('payments', 'PaymentEvent')
    with connection.cursor() as cursor:
        cursor.execute(f'CREATE INDEX {INDEX_NAME} ON {model._meta.db_table} USING HASH ((data->\'id\'));')


def drop_index(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute(f'DROP INDEX {INDEX_NAME};')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20230424_1222'),
    ]

    operations = [
        migrations.RunPython(create_index, drop_index)
    ]
