# Generated by Django 2.2 on 2023-05-03 11:09

from django.db import migrations


def convert_xsollaproject(apps, schema_editor):
    XsollaProject = apps.get_model('payments', 'XsollaProject')
    PaymentProject = apps.get_model('payments', 'PaymentProject')

    projects = [
        PaymentProject(
            payment_system_name='xsolla',
            id=xsolla_project.id,
            game_id=xsolla_project.game_id,
            secret_key=xsolla_project.secret_key
        )
        for xsolla_project in XsollaProject.objects.all()
    ]
    PaymentProject.objects.bulk_create(projects)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0066_recommended'),
        ('payments', '0005_convert_xsollatransactions_to_internaltransaction'),
    ]

    operations = [
        migrations.RunPython(convert_xsollaproject)
    ]
