# Generated by Django 2.2 on 2023-08-23 08:35

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


def default_logins():
    """Set the first day to True (visited) by default."""
    return [True] + ([False] * 13)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0007_add_payment_system_name_to_pedningevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginsLoyaltyProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='start date')),
                ('accepted', models.BooleanField(default=False, editable=False, verbose_name='credited to account')),
                ('accepted_date', models.DateField(editable=False, null=True, verbose_name='date of crediting to account')),
                ('accepted_bonuses', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='accepted bonuses')),
                ('logins', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=default_logins, editable=False, size=28)),
                ('saved_days', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), default=list, editable=False, size=None)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='logins_loyalty_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login loyalty program',
                'verbose_name_plural': 'Login loyalty programs',
            },
        ),
        migrations.AddConstraint(
            model_name='loginsloyaltyprogram',
            constraint=models.UniqueConstraint(condition=models.Q(accepted=False), fields=('user',), name='unique_user_accepted_logins_loyalty_program'),
        ),
        migrations.AddConstraint(
            model_name='loginsloyaltyprogram',
            constraint=models.CheckConstraint(check=models.Q(accepted_bonuses__gte=0), name='accepted_bonuses_gte_0'),
        ),
    ]
