# Generated by Django 2.2 on 2023-09-23 12:17

import apps.payments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20230823_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLPConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('full_duration', models.PositiveSmallIntegerField()),
                ('stage_duration', models.PositiveSmallIntegerField()),
                ('lives', models.PositiveSmallIntegerField()),
                ('hot_streak_factor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_hot_streak', models.PositiveSmallIntegerField()),
                ('weekly_logins_hot_streak', models.PositiveSmallIntegerField()),
                ('bonus_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'LoginsLoyaltyProgram config',
                'verbose_name_plural': 'LoginsLoyaltyProgram configs',
            },
        ),
        migrations.AddConstraint(
            model_name='llpconfig',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('active',), name='active_constraint'),
        ),
        migrations.RemoveField(
            model_name='loginsloyaltyprogram',
            name='saved_days',
        ),
    ]
