# Generated by Django 2.2 on 2023-09-23 12:19

from django.db import migrations


def create_config(apps, schema_editor):
    LLPConfig = apps.get_model('payments', 'LLPConfig') # noqa
    LLPConfig.objects.create(
        active=True, full_duration=14, stage_duration=7, lives=2, hot_streak_factor=0.15, serial_hot_streak=2,
        weekly_logins_hot_streak=3, bonus_per_day=10
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20230923_1217'),
    ]

    operations = [
        migrations.RunPython(create_config, migrations.RunPython.noop)
    ]
