# Generated by Django 2.2 on 2023-09-23 12:30

from datetime import timedelta

from django.db import migrations


def transfer(apps, schema_editor):
    LoginsLoyaltyProgram = apps.get_model('payments', 'LoginsLoyaltyProgram') # noqa
    Visit = apps.get_model('stat', 'Visit')  # noqa
    batch_size = 999 if schema_editor.connection.vendor == 'sqlite' else 2000

    for program in LoginsLoyaltyProgram.objects.all():
        visits = [
            Visit(user_id=program.user_id, datetime=program.start_date + timedelta(days=day))
            for day, is_visited in enumerate(program.logins)
            if is_visited
        ]
        Visit.objects.bulk_create(visits, batch_size=batch_size)


def back(apps, schema_editor):
    LoginsLoyaltyProgram = apps.get_model('payments', 'LoginsLoyaltyProgram')  # noqa
    Visit = apps.get_model('stat', 'Visit')  # noqa
    to_update = []
    for program in LoginsLoyaltyProgram.objects.all():
        visits = Visit.objects.filter(user_id=program.user_id, datetime__gte=program.start_date) \
            .dates('datetime', 'day')
        program.logins = [False] * 14
        for visit_date in visits:
            program.logins[(visit_date - program.start_date).days] = True

        to_update.append(program)
    batch_size = 999 if schema_editor.connection.vendor == 'sqlite' else 2000
    LoginsLoyaltyProgram.objects.bulk_update(to_update, fields=['logins'], batch_size=batch_size)



class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0010_default_loyalty_config'),
        ('stat', '0011_auto_20230923_1210'),
    ]

    operations = [
        migrations.RunPython(transfer, back)
    ]
