# Generated by Django 2.2 on 2023-09-23 13:09

import apps.payments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_data_logins_to_visit_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsloyaltyprogram',
            name='logins',
        ),
        migrations.AddField(
            model_name='loginsloyaltyprogram',
            name='config',
            field=models.ForeignKey(default=apps.payments.models.default_config, on_delete=django.db.models.deletion.SET_DEFAULT, to='payments.LLPConfig'),
        ),
    ]
