export default {
  id: 210461,
  is_you: false,
  action: 'followed_user',
  created: '2018-03-06T21:02:13.716790Z',
  user: {
    id: 6001,
    username: 'Mobvil',
    slug: 'mobvil',
    full_name: 'Evgeniy Korobka',
    avatar: null,
    games_count: 1,
    collections_count: 0,
    following: false,
  },
  users: {
    count: 17,
    results: [
      {
        id: 2550,
        username: 'lr33',
        slug: 'lr33',
        full_name: 'Dmitri Bourkovski',
        avatar: null,
        games_count: 215,
        collections_count: 0,
        following: false,
      },
      {
        id: 5569,
        username: 'aleksandr75',
        slug: 'aleksandr75',
        full_name: 'Aleksandr Agapitov',
        avatar: null,
        games_count: 0,
        collections_count: 0,
        following: false,
      },
      {
        id: 5485,
        username: 'bigwhitegames',
        slug: 'bigwhitegames',
        full_name: 'Леонид Сиротин',
        avatar: null,
        games_count: 0,
        collections_count: 0,
        following: false,
      },
      {
        id: 1019,
        username: 'nikita15',
        slug: 'nikita15',
        full_name: 'Nikita Grigorovich',
        avatar: null,
        games_count: 4,
        collections_count: 2,
        following: false,
      },
      {
        id: 2240,
        username: 'TimFadeev',
        slug: 'timfadeev',
        full_name: 'Tim Fadeev',
        avatar: null,
        games_count: 75,
        collections_count: 0,
        following: false,
      },
      {
        id: 2536,
        username: 'maxim80',
        slug: 'maxim80',
        full_name: 'Maxim Fomichev',
        avatar: null,
        games_count: 0,
        collections_count: 0,
        following: false,
      },
      {
        id: 1866,
        username: 'vitaliy43',
        slug: 'vitaliy43',
        full_name: 'Vitaliy Ischenko',
        avatar: null,
        games_count: 105,
        collections_count: 1,
        following: false,
      },
      {
        id: 287,
        username: 'trtrtr',
        slug: 'trtrtr',
        full_name: 'Maxim',
        avatar: null,
        games_count: 860,
        collections_count: 0,
        following: false,
      },
      {
        id: 4155,
        username: 'alexandra49',
        slug: 'alexandra49',
        full_name: 'Alexandra Pestretsova',
        avatar: null,
        games_count: 12,
        collections_count: 0,
        following: false,
      },
      {
        id: 2689,
        username: 'igor03',
        slug: 'igor03',
        full_name: 'Igor Matsanyuk',
        avatar: null,
        games_count: 0,
        collections_count: 0,
        following: false,
      },
      {
        id: 2575,
        username: 'lerika',
        slug: 'lerika',
        full_name: 'Lerika Mallayeva',
        avatar: null,
        games_count: 3,
        collections_count: 0,
        following: false,
      },
      {
        id: 4998,
        username: 'victor62',
        slug: 'victor62',
        full_name: 'Victor Zaletov',
        avatar: null,
        games_count: 282,
        collections_count: 0,
        following: false,
      },
      {
        id: 478,
        username: 'maxkamm',
        slug: 'maxkamm',
        full_name: 'Max',
        avatar: null,
        games_count: 219,
        collections_count: 0,
        following: false,
      },
      {
        id: 476,
        username: 'antokos',
        slug: 'antokos',
        full_name: 'Anton Kotelnikov',
        avatar: null,
        games_count: 124,
        collections_count: 2,
        following: false,
      },
      {
        id: 3879,
        username: 'beatshapers',
        slug: 'beatshapers',
        full_name: 'Alexey Menshikov',
        avatar: null,
        games_count: 3,
        collections_count: 0,
        following: false,
      },
      {
        id: 3472,
        username: 'john05',
        slug: 'john05',
        full_name: 'John Uke',
        avatar: null,
        games_count: 111,
        collections_count: 0,
        following: false,
      },
      {
        id: 1803,
        username: 'alex41',
        slug: 'alex41',
        full_name: 'Alex Spasskiy',
        avatar: null,
        games_count: 0,
        collections_count: 0,
        following: false,
      },
    ],
  },
};
