# Generated by Django 2.2 on 2023-09-08 12:23

import apps.apk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True, verbose_name='version')),
                ('app_file', models.FileField(upload_to=apps.apk.models.apk_app_file_path, verbose_name='file')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('active', models.BooleanField(db_index=True, default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'APK file',
                'verbose_name_plural': 'APK files',
            },
        ),
        migrations.AddConstraint(
            model_name='apk',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('active',), name='apk_active_constraint'),
        ),
    ]
