version: '3'

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.3.0
    links:
      - elastic
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
    ports:
      - 5601:5601

  flower:
    container_name: flower
    build:
      dockerfile: config/develop/Dockerfile
      context: ./
    image: rawg-web
    command: celery flower -A apps --port=5555 --workdir project
    volumes:
      - ./:/app/
    links:
      - rabbit
    ports:
      - 5555:5555

  adminer:
    image: adminer
    ports:
      - 8080:8080
    links:
      - postgres
