# Generated by Django 2.2.15 on 2020-12-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('charts', '0001_squashed_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecreditperson',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamefull',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamegenre',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gamereleased',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gametoplay',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gameupcoming',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gameyear',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
