# Generated by Django 2.2.27 on 2023-11-06 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0075_auto_20230830_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='games.Game')),
            ],
            options={
                'verbose_name': 'OAuth2 client',
                'verbose_name_plural': 'OAuth2 clients',
            },
        ),
    ]
