version: "3"

services:
  postgres:
    container_name: rawg-postgres
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - config/develop/env
#    ports:
#      - 5432:5432

  memcached:
    container_name: rawg-memcached
    image: memcached
    command: memcached -m 5m
#    ports:
#      - 11211:11211

  redis:
    container_name: rawg-redis
    image: redis:7.0.5
    volumes:
      - redis:/data
    sysctls:
      - net.core.somaxconn=1024
    command: redis-server --save 60 1 --loglevel warning

  mongo:
    container_name: rawg-mongo
    image: mongo:latest
    command: --setParameter cursorTimeoutMillis=259200000
    volumes:
      - mongo:/data/db
#    ports:
#      - 27017:27017

  elastic:
    container_name: rawg-elastic
    image: elasticsearch:7.17.10
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "indices.query.bool.max_clause_count=5000"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
#    ports:
#      - 9200:9200

  rabbit:
    hostname: rabbit
    container_name: rawg-rabbit
    image: rabbitmq:latest
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  celery:
    container_name: rawg-celery
    build:
      dockerfile: config/Dockerfile
      context: ./
    image: rawg-web
    command: ["bash", "/app/config/wait-for-it.sh", "postgres:5432", "rabbit:5672", "--timeout=60", "--",
              "celery", "worker", "-A", "apps", "-l", "info", "-Q", "critical,high,normal,low,denormalize,stat,video",
              "--workdir", "project", "-n", "celery@celery"]
    volumes:
      - ./:/app/
    env_file:
      - config/develop/env
    links:
      - rabbit
      - memcached

  celery-beat:
    container_name: rawg-celery-beat
    build:
      dockerfile: config/Dockerfile
      context: ./
    image: rawg-web
    command: ["bash", "/app/config/wait-for-it.sh", "postgres:5432", "rabbit:5672", "--timeout=60", "--",
              "celery", "beat", "-A", "apps", "-l", "info", "--workdir", "project",
              "-s", "../data/celerybeat.db", "--pidfile="]
    volumes:
      - ./:/app/
    env_file:
      - config/develop/env
    links:
      - rabbit
      - memcached

#  poxa:
#    container_name: rawg-poxa
#    image: edgurgel/poxa-automated:v1.0.0
##    ports:
##      - 8001:8080
#    environment:
#      - WEB_HOOK=http://web:8000/api/pusher/webhook

  web:
    container_name: rawg-web
    build:
      dockerfile: config/Dockerfile
      context: ./
    image: rawg-web
    entrypoint: ["bash", "/app/config/wait-for-it.sh", "postgres:5432", "--timeout=60", "--",
                 "bash", "/app/config/wait-for-postgres.sh", "postgres",
                 "bash", "/app/config/web.sh"]
    volumes:
      - ./:/app/
      - papi:/app/data/api/
    env_file:
      - config/develop/env
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - mongo
      - memcached
      - redis
      - rabbit
      - elastic

volumes:
  postgres:
  redis:
  mongo:
  elastic:
  rabbitmq:
  papi:
